### ISSUE TITLE
Clicking Actions on new insult overwrites insult value

### ISSUE THREAD

**Issue by ennegineer** [ChristianPayne/ennesults-rs#28]
Behavior: add a new insult, click the Actions menu and click Edit Insult, and the value changes to the previous insult. 

Expected behavior: add a new insult, click the Actions menu and click Edit Insult, and the value remains unchanged. 

Same bug appears for Comebacks and Announcements.

**Comment by ChristianPayne** [comment]
Fixed in v1.3.1
